name: Push to Docker Hub

on: [workflow_dispatch]  # Ğ¢Ğ¾Ğ»ÑŒĞºĞ¾ Ğ²Ñ€ÑƒÑ‡Ğ½ÑƒÑ

jobs:
  push:
    runs-on: ubuntu-latest
    
    steps:
    - name: ğŸ“¥ Ğ¡ĞºĞ°Ñ‡Ğ°Ñ‚ÑŒ ĞºĞ¾Ğ´
      uses: actions/checkout@v4
    
    - name: ğŸ”§ Ğ¡Ğ¾Ğ±Ñ€Ğ°Ñ‚ÑŒ
      run: docker build -t firuzs/lab-project:latest .
    
    - name: ğŸ” Ğ’Ğ¾Ğ¹Ñ‚Ğ¸ Ğ² Docker Hub
      run: |
        docker login -u firuzs -p ${{ secrets.DOCKER_PASSWORD }}
    
    - name: ğŸš€ Ğ—Ğ°Ğ³Ñ€ÑƒĞ·Ğ¸Ñ‚ÑŒ
      run: docker push firuzs/lab-project:latest
